server:
  port: 10086
spring:
  application:
    name: zull-gateway
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.131:10000/eureka
    instance:
      prefer-ip-address: true # 当调用getHostname获取实例的,返回ip而不是host名称
      ip-address: 192.168.1.131 # 指定自己的ip信息，不指定的话会自己寻找

zuul:
  prefix: /api/
  routes:
    one: /dept/**
    dept-customer: /demo/**
