server:
  port: 10000
spring:
  application:
    name: cloud-eureka-server
  host: 192.168.1.131
eureka:
  client:
    service-url:
      defaultZone: http://${spring.host}:${server.port}/eureka
    register-with-eureka: false #不注册自己，列表当中看不到自己
    fetch-registry: false #不注册自己